FROM node:18-alpine

# Variables.
#ARG UID
#ARG GID

# Update y upgrade, además, añado paquetes.
RUN apk -U upgrade
RUN apk add neovim

# Añado directorio de trabajo.
WORKDIR /angular

# Creo directorio y permisos.
RUN mkdir /angular/node_modules 
#RUN chown -R "${UID}":"${GID}" /angular

# Copio ficheros por si los hubiera.
#COPY --chown="${UID}":"${GID}" . /angular
COPY . /angular

# Instalo última version de npm.
RUN npm install -g npm@latest

# Instalo CLI de Angular.
RUN npm install -g @angular/cli@latest

# Expongo el puerto de trabajo.
EXPOSE 4200

# Defino usuario.
#USER node

# Ejecuto terminal.
CMD ["/bin/sh", "-c", "tail -f /dev/null"]
