FROM  mongo:6.0.8-jammy

# Variables.

#ARG UID
#ARG GID

# Copiamos configuración de MongoDB y asignamos permisos.

# COPY --chown="${UID}":"${GID}" ./mongod.conf /etc/mongod.conf
COPY ./mongod.conf /etc/mongod.conf